[package]
name = "H1-Trading-Engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rustc-hash = "2.1.1"


[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "engine_bench"
harness = false

[profile.release]
debug = true